config/routes.rb
Rails.application.routes.draw do
  resources :businesses
  devise_for :users
  get '/businesses/new' => 'home#index', as: "first_route"
  # get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "new_task" ,to: "tasks#new"

  post "new_task", to: "tasks#create"

  get "admin_view", to: "businesses#admin_view"
  # resources :tasks
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
    has_and_belongs_to_many :users
    has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
    enum task_type: {
        feature: 0,
        bug: 1
      }       
  belongs_to :business
  validates :title, presence: true, uniqueness: true

end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum user_type: {
      admin: 0,
      writing_broker: 1,
      support: 2
    }       

    has_and_belongs_to_many :businesses

    #  Mapping integer values to string for pundit
    after_initialize do
      if self.new_record?
        self.user_type ||= :admin
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?


    include Pundit

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  
    private
  
    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
    end


    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :user_type])
    end

    def after_sign_in_path_for(resource)
        businesses_path
    end

    # def index
    #     @users = User.order(created_at: :desc)
    #     authorize @users
    # end

    
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: %i[ show edit update destroy ]
  before_action :authenticate_user! 
  include Pundit
  # GET /businesses or /businesses.json
  def index
    # @businesses = Business.all
    # user.user_type
    # authorize @businesses
    # @businesses = policy_scope(Business).order(b_name: :desc)
    if current_user.user_type == 'admin'
      # puts current_user
      @businesses = Business.all
    else
      @businesses = current_user.businesses
      # puts "abc"
    end
  end

  # GET /businesses/1 or /businesses/1.json
  def show
  end

  # admin view
  def admin_view
    if params[:business] && params[:business][:id].present?
      # debugger
      @business = Business.find(params[:business][:id])
    else
      @business = Business.first
    end
    @tasks = @business.tasks
  end


  # GET /businesses/new
  def new
    puts "========================================================="
    @business = Business.new
    authorize @business
  end

  # GET /businesses/1/edit
  def edit
    @business = Business.find(params[:id])
    authorize @business
  end
  
  # def edit
  #   @business = Business.find(params[:id])
  #   authorize @business
    
  #   if @business.edit(business_params)
  #     flash[:notice] = "\"#{@business.b_name}\" HEHEHEHEHHEHEHHEHE Editted"
  #     redirect_to @business
  #   else
  #     flash.now[:alert] = "There was an error Editting the Business."
  #     render :edit
  #   end
  # end  



  # POST /businesses or /businesses.json
  def create
    @business = Business.new(business_params)
    authorize @business
    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: "Business is successfully created." }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1 or /businesses/1.json

  def update
    @business = Business.find(params[:id])
    authorize @business
    
    if @business.update(business_params)
      flash[:notice] = "\"#{@business.b_name}\" Business is successfully Updated."
      redirect_to @business
    else
      flash.now[:alert] = "There was an error Updating the Business."
      render :edit
    end
  end  


  # def update
  #   respond_to do |format|
  #     if @business.update(business_params)
  #       format.html { redirect_to @business, notice: "Business was successfully updated." }
  #       format.json { render :show, status: :ok, location: @business }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @business.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end


    def destroy
      @business = Business.find(params[:id])
      authorize @business
      
      if @business.destroy
        flash[:notice] = "\"#{@business.b_name}\" Business is successfully removed."
        redirect_to @business
      else
        flash.now[:alert] = "There was an error deleting the Business."
        render :show
      end
    end

  # DELETE /businesses/1 or /businesses/1.json
  # def destroy
  #   @business.destroy
  #   respond_to do |format|
  #     format.html { redirect_to businesses_url, notice: "Business was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def business_params
      
      params.require(:business).permit(:b_name, :description).merge(user_ids: params[:users][:id].reject(&:empty?))
      
    end



    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :authenticate_user! 
  # before_action :configure_permitted_parameters, if: :devise_controller?
  # protected

  # def configure_permitted_parameters
  #     devise_parameter_sanitizer.permit(:sign_up, keys: [:title, :task_type])
  # end

  def new
    @task = Task.new
    @tasks = Task.all
  end

  def create
    @task = Task.new(task_params)
    respond_to do |format|

        if @task.save
          format.html { redirect_to new_task_path, notice: "Task was successfully created." }
          format.json { render :show, status: :created, location: @task }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end

    def task_params
      params.require(:task).permit(:title, :due_date, :task_type, :image, :task_type,:business_id)
      # params.require(:business).permit(:b_name, :description).merge(user_ids: params[:users][:id].reject(&:empty?))
    end
  end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/businesses/_form.html.erb
<%= form_with(model: business) do |form| %>
  <% if business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
        <% business.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :Business_name %>
    <%= form.text_field :b_name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :Available_users %><br/>
    <%= collection_select(:users, :id, User.all, :id, :name, {}, { :multiple => true }) %>  
  </div>
 
<div class="field">
    <% form.label "Available Users in Checkbox form" %><br />
      <% form.collection_check_boxes :user_ids, User.all, :id, :name do |b| %>
       <div class="collection-check-box">
          <% b.check_box %>
          <% b.label %>
      </div>
    <% end %>
  </div>

 <div class="form-group">

 </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/businesses/admin_view.html.erb
<center><h1> This is admin view </h1></center>


    <h1> Registered Business </h1>
    <%= collection_select(:business, :id, Business.all, :id, :b_name, {}, data:{remote: true}) %> 

    <div id="tasks">
        <%= render "tasks/index", tasks: @tasks %>
        
    </div>    

app/views/businesses/admin_view.js.erb
document.getElementById("tasks").innerHTML = "<%= escape_javascript(render partial: "tasks/index", locals: { tasks: @tasks }) %>"

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Show', @business, class:"btn btn-info" %> |
<%= link_to 'Back', businesses_path, class:"btn btn-info" %>

app/views/businesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Businesses</h1>

<table  class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Business</th>
      <th>Description</th>
      <th>Team Members</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>  
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.b_name %></td>
        <td><%= business.description %></td>
        <td><%= business.users.pluck(:name).join(",") %></td>
        <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td>
        <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Create New Business', new_business_path , class:"btn btn-dark"%>
<%= link_to 'Create New Task', new_task_path , class:"btn btn-dark"%>

app/views/businesses/new.html.erb
<h1>Create New Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>



<div class="jumbotron">
  <h1 class="display-4"> <%= @business.b_name %>: </h1>
  <p class="lead"><%= @business.description %></p>
  <hr class="my-4">
  <p>  <strong>Team Members:</strong><%= @business.users.pluck(:name).join(", ")  %></p>
  <%= link_to 'Edit', edit_business_path(@business), class:"btn btn-info" %> 
  <%= link_to 'Back', businesses_path(@business), class:"btn btn-info" %> 
</div>



<%
=begin%>
 <p>
  <strong>Business name:</strong>
  <%= @business.b_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @business.description %>
</p>
<p>
  <strong>Team Members:</strong>
  <%= @business.users.pluck(:name).join(", ")  %>
</p>


<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %> 
<%
=end%>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light navbar-dark bg-dark">
  <%= link_to "Business Management", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>

      <% if user_signed_in? %>
          <li class="nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link"%> 
              <%= puts current_user.name%>
          </li>
          <li class="nav-item">
              <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link"%> 
          </li>
          <li class="nav-item">
              <%= link_to "Businesses", businesses_path, class: "nav-link"%> 
          </li>
          <li class="nav-item">
              <%= link_to "Tasks", new_task_path, class: "nav-link"%> 
          </li>
          <li class="nav-item">
              <%= link_to "View Tasks", admin_view_path, class: "nav-link"%> 
          </li>
          
      <% else %>
          <li class="nav-item">
              <%= link_to "Sign in", new_user_session_path, class: "nav-link"%> 
          </li>
          <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>

    <% end %>
    </ul>
  </div>

</nav>

<body>
</body>

app/views/home/index.html.erb
<h1> <center> Welcome to the Home Page </center</h1>
<br/><br/>
<div >
  <p>
    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
  </p>

  <p>
    Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
  </p>

  <p>
    The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.
  </p>
</div>
<%
=begin%>
 <%=begin%>
 <nav class="navbar navbar-expand-lg bg-light navbar-dark bg-dark">
  <%= link_to "Business Management", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>

      <% if user_signed_in? %>
          <li class="nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link"%> 
              <%= puts current_user.name%>
          </li>
          <li class="nav-item">
              <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link"%> 
          </li>
      <% else %>
          <li class="nav-item">
              <%= link_to "Sign in", new_user_session_path, class: "nav-link"%> 
          </li>
          <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>

    <% end %>
    </ul>
  </div>

</nav>

<body>
</body> 
<%
=end%> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </head>

  <body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


    <div class="container">
        <%= render "home/header" %>
        <%= yield %>
    </div>

  </body>
</html>

app/views/tasks/_index.html.erb
<br/> <br />

<% tasks.each do |item| %>
    <div class="jumbotron">
        <h1 class="display-4"><%= item.title %></h1>
        <p class="lead"><strong>DATE:</strong>
            <%= item.due_date %>
        </p>
    </div>
<% end %>

app/views/tasks/new.html.erb
<h1>Welcome to the tasks </h1>
<%= form_with model: @task, url: new_task_path do |form| %>
    <% if @task.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@task.errors.count, "error") %> prohibited this @task from being saved:</h2>
            <ul>
                <% @task.errors.each do |error| %>
                <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= form.text_field :title, class: "form-control", placeholder: "Enter task title" %>
    </div>
    <div class="form-group">
        <%= form.label :Due_date %><br />
        <%= form.date_select :due_date, class: "form-control" %>
    </div>
    <%
=begin%>
 <div class="form-group">
    <%= form.file_field :image %>
    </div>
     
<%
=end%>
    <div class="field">
        <%= form.label :Task_type %><br />
        <%= form.select :task_type, Task.task_types.keys, autofocus: true, autocomplete: "" %>
    </div>
    
    <div class="field">
        <%= form.label :Registered_businesses %><br />  
        <% form.select :"business_id", options_for_select(Business.all.pluck(:b_name)) %>
        <%= form.select :business_id, Business.all.map { |b| [b.b_name, b.id] }, autofocus: true, autocomplete: "" %>
    </div>
    
<div class="mb-3">
    <%= form.submit "Create Task", class: "btn btn-primary" %>
</div>
<% end %>